### PR TITLE
Ticket -> Execution flow

### PR DESCRIPTION
**Pull request by aiswaryasankar**
wip

### CODE REVIEW

**Comment by pedroCollogno** [comment]
Rebased

**Comment by pedroCollogno** [comment]
Still getting 
```
AttributeError: st.session_state has no attribute "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
```

**Comment by pedroCollogno** [comment]
We need to also inform the user that they need an OpenAI token when onboarding

**Comment by pedroCollogno** [comment]
# Description

Create the `Architect` class, that allows users to cut Features into small tasks and push them to their Trello backlog.
The interface is an interactive chat session, during which the user interacts with the agent. The agent pulls the entire codebase from the GitHub repo to get relevant codepointers for the tickets.

Fixes #7 

## Type of change

- [X] Refactoring
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

This was tested manually, see screenshots below

## Chat session

image

## Trello board before

Screenshot 2024-03-27 at 3 07 36 PM

## Trello board after

Screenshot 2024-03-27 at 3 09 03 PM


# Checklist:

- [ ] I have performed a self-review of my code
- [ ] My commits are self contained changes with descriptive messages 
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] (If relevant) I have written a test for my change
- [ ] New and existing tests pass 
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] (If relevant) If there's a visual change, I added a screenshot to the PR

**Review by axelpey — APPROVED** [review]
LGTM

**Pull request merged**
